# Generated by Django 5.2.8 on 2025-11-24 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Должность"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("property_management", "Property management"),
                            ("hotel_management", "Hotel management"),
                            ("cleaning", "Cleaning"),
                            ("maintenance", "Maintenance"),
                            ("finance", "Finance"),
                            ("marketing", "Marketing"),
                            ("it", "IT"),
                            ("hr", "HR"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Подразделение",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CEO", "CEO"),
                            ("COO", "COO"),
                            ("CFO", "CFO"),
                            ("CBDO", "CBDO"),
                            ("HotelDirector", "Hotel Director"),
                            ("GM", "General Manager"),
                            ("FrontDesk", "Front Desk"),
                            ("Cleaning", "Cleaning"),
                            ("Maintenance", "Maintenance"),
                            ("Quality", "Quality"),
                            ("Marketing", "Marketing"),
                            ("Finance", "Finance"),
                            ("IT", "IT"),
                            ("HR", "HR"),
                        ],
                        max_length=50,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=32, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Рабочий email"
                    ),
                ),
                (
                    "is_active_employee",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "schedule",
                    models.TextField(blank=True, verbose_name="График работы"),
                ),
                (
                    "access_notes",
                    models.TextField(
                        blank=True,
                        help_text="Текстовое описание особенностей доступа. Сами права настраиваются через группы.",
                        verbose_name="Права доступа (описание)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "properties",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Например, GM закреплён за конкретным отелем.",
                        related_name="staff_members",
                        to="properties.property",
                        verbose_name="Закреплённые объекты",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["full_name"],
            },
        ),
    ]
