# Generated by Django 5.2.8 on 2025-11-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(
                choices=[
                    ("CEO", "CEO"),
                    ("COO", "COO"),
                    ("PropertyManager", "Property Manager"),
                    ("CFO", "CFO"),
                    ("CBDO", "CBDO"),
                    ("HotelDirector", "Hotel Director"),
                    ("GM", "General Manager"),
                    ("FrontDesk", "Front Desk"),
                    ("Cleaning", "Cleaning"),
                    ("Maintenance", "Maintenance"),
                    ("Quality", "Quality"),
                    ("Marketing", "Marketing"),
                    ("Finance", "Finance"),
                    ("IT", "IT"),
                    ("HR", "HR"),
                ],
                max_length=50,
                verbose_name="Роль",
            ),
        ),
    ]
