# Generated by Django 5.2.8 on 2025-11-24 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("owners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("residential_short", "Жилая (посуточно)"),
                            ("residential_long", "Жилая (долгосрочно)"),
                            ("commercial", "Коммерческая"),
                            ("hotel", "Отель / апарт-отель"),
                        ],
                        max_length=32,
                        verbose_name="Тип объекта",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название объекта"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                (
                    "district",
                    models.CharField(blank=True, max_length=100, verbose_name="Район"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_management", "В управлении"),
                            ("onboarding", "На подключении"),
                            ("archived", "Архив"),
                        ],
                        default="in_management",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_properties",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный менеджер",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="owners.owner",
                        verbose_name="Собственник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объект недвижимости",
                "verbose_name_plural": "Объекты недвижимости",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("room", "Номер"),
                            ("apartment", "Апартамент"),
                            ("commercial_unit", "Коммерческая единица"),
                        ],
                        max_length=32,
                        verbose_name="Тип юнита",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=100, verbose_name="Код / Название"),
                ),
                (
                    "floor",
                    models.IntegerField(blank=True, null=True, verbose_name="Этаж"),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Метраж, м²",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Вместимость"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("maintenance", "На ремонте"),
                            ("blocked", "Заблокирован"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="properties.property",
                        verbose_name="Объект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Юнит",
                "verbose_name_plural": "Юниты",
                "ordering": ["property", "code"],
                "unique_together": {("property", "code")},
            },
        ),
    ]
