# Generated by Django 5.2.8 on 2025-11-24 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_unit_description_unitphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="brand_name",
            field=models.CharField(
                blank=True,
                help_text="Если отель работает под брендом/сетью.",
                max_length=255,
                verbose_name="Бренд / сеть",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="checkin_time",
            field=models.TimeField(
                blank=True,
                help_text="Применимо для объектов типа 'hotel'.",
                null=True,
                verbose_name="Время заезда",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="checkout_time",
            field=models.TimeField(
                blank=True,
                help_text="Применимо для объектов типа 'hotel'.",
                null=True,
                verbose_name="Время выезда",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="has_reception",
            field=models.BooleanField(
                default=False,
                help_text="Применимо для объектов типа 'hotel'.",
                verbose_name="Есть ресепшен",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="hotel_star_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Для hotel-объектов: количество звёзд (1–5).",
                null=True,
                verbose_name="Звёздность отеля",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="rooms_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Ориентировочное количество номеров (может отличаться от числа юнитов).",
                null=True,
                verbose_name="Количество номеров",
            ),
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название категории"),
                ),
                (
                    "base_capacity",
                    models.PositiveIntegerField(
                        help_text="Количество гостей по умолчанию.",
                        verbose_name="Базовая вместимость",
                    ),
                ),
                (
                    "base_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Средняя площадь, м²",
                    ),
                ),
                (
                    "amenities",
                    models.TextField(
                        blank=True,
                        help_text="Описание основных удобств и особенностей категории.",
                        verbose_name="Удобства",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_types",
                        to="properties.property",
                        verbose_name="Отель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип номера",
                "verbose_name_plural": "Типы номеров",
                "ordering": ["property", "name"],
            },
        ),
        migrations.AddField(
            model_name="unit",
            name="room_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="units",
                to="properties.roomtype",
                verbose_name="Тип номера",
            ),
        ),
    ]
