# Generated by Django 5.2.8 on 2025-11-24 03:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("owners", "0001_initial"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(max_length=100, verbose_name="Категория расхода"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=10, verbose_name="Валюта"
                    ),
                ),
                ("expense_date", models.DateField(verbose_name="Дата расхода")),
                (
                    "contractor",
                    models.CharField(
                        blank=True,
                        help_text="Название подрядчика, если есть.",
                        max_length=255,
                        verbose_name="Подрядчик / контрагент",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="properties.property",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="properties.unit",
                        verbose_name="Юнит",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расход",
                "verbose_name_plural": "Расходы",
                "ordering": ["-expense_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OwnerReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Год")),
                ("month", models.PositiveSmallIntegerField(verbose_name="Месяц")),
                (
                    "income_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Сумма доходов",
                    ),
                ),
                (
                    "expense_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Сумма расходов",
                    ),
                ),
                (
                    "net_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Чистая прибыль",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_reports",
                        to="owners.owner",
                        verbose_name="Собственник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчёт собственнику",
                "verbose_name_plural": "Отчёты собственникам",
                "ordering": ["-year", "-month", "owner"],
                "unique_together": {("owner", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="FinanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("income", "Доход"),
                            ("expense", "Расход"),
                            ("adjustment", "Корректировка"),
                        ],
                        max_length=20,
                        verbose_name="Тип записи",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Например: аренда, уборка, ремонт, комиссия OTA и т.п.",
                        max_length=100,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=10, verbose_name="Валюта"
                    ),
                ),
                ("operation_date", models.DateField(verbose_name="Дата операции")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_records",
                        to="bookings.booking",
                        verbose_name="Бронирование",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_records",
                        to="owners.owner",
                        verbose_name="Собственник",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_records",
                        to="properties.property",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "owner_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_records",
                        to="finance.ownerreport",
                        verbose_name="Отчёт собственнику",
                    ),
                ),
            ],
            options={
                "verbose_name": "Финансовая запись",
                "verbose_name_plural": "Финансовые записи",
                "ordering": ["-operation_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Год")),
                ("month", models.PositiveSmallIntegerField(verbose_name="Месяц")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма к выплате"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=10, verbose_name="Валюта"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("planned", "Запланирована"), ("paid", "Выплачена")],
                        default="planned",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "payout_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата выплаты"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="owners.owner",
                        verbose_name="Собственник",
                    ),
                ),
                (
                    "owner_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payouts",
                        to="finance.ownerreport",
                        verbose_name="Отчёт собственнику",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выплата собственнику",
                "verbose_name_plural": "Выплаты собственникам",
                "ordering": ["-year", "-month", "owner"],
                "unique_together": {("owner", "year", "month")},
            },
        ),
    ]
