# Generated by Django 5.2.8 on 2025-11-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownerreport",
            name="is_sent",
            field=models.BooleanField(
                default=False, verbose_name="Отправлен собственнику"
            ),
        ),
        migrations.AddField(
            model_name="ownerreport",
            name="is_signed",
            field=models.BooleanField(
                default=False, verbose_name="Подписан собственником"
            ),
        ),
        migrations.AddField(
            model_name="ownerreport",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата отправки"
            ),
        ),
        migrations.AddField(
            model_name="ownerreport",
            name="signed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата подписания"
            ),
        ),
    ]
