# Generated by Django 5.2.8 on 2025-11-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_center", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Имя сервера"
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        help_text="Например: http://localhost:3001/mcp",
                        max_length=500,
                        verbose_name="Базовый URL MCP",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "tools_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='JSON c описанием инструментов этого MCP‑сервера. Например: {"tools": [{"name": "read_file", ...}]}',
                        verbose_name="Конфигурация инструментов",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "MCP‑сервер",
                "verbose_name_plural": "MCP‑серверы",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="agent",
            name="mcp_servers",
            field=models.ManyToManyField(
                blank=True,
                help_text="К каким MCP‑серверам имеет доступ этот агент.",
                related_name="agents",
                to="ai_center.mcpserver",
                verbose_name="MCP‑серверы",
            ),
        ),
    ]
