# Generated by Django 5.2.8 on 2025-11-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_center", "0002_mcpserver_agent_mcp_servers"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openai_api_key",
                    models.CharField(
                        blank=True,
                        help_text="Ключ для OpenAI Chat API. В продакшене лучше хранить в переменных окружения.",
                        max_length=255,
                        verbose_name="OpenAI API key",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "AI‑настройки",
                "verbose_name_plural": "AI‑настройки",
            },
        ),
    ]
