# Generated by Django 5.2.8 on 2025-11-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_center", "0003_aisettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aisettings",
            name="openai_api_key",
            field=models.CharField(
                blank=True,
                help_text="Ключ для OpenAI Chat API. Используется только в режиме DEBUG=True. В продакшене ключ должен быть задан через переменную окружения OPENAI_API_KEY или в settings.OPENAI_API_KEY.",
                max_length=255,
                verbose_name="OpenAI API key",
            ),
        ),
    ]
