# Generated by Django 5.2.8 on 2025-11-25 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0003_property_brand_name_property_checkin_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Базовая цена"
                    ),
                ),
                (
                    "recommended_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Рекомендованная цена",
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Минимальная цена"
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Максимальная цена",
                    ),
                ),
                (
                    "occupancy_7d",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Загрузка за 7 дней"
                    ),
                ),
                (
                    "occupancy_30d",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Загрузка за 30 дней"
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        help_text="low, shoulder, high",
                        max_length=20,
                        verbose_name="Сезон",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечание")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_recommendations",
                        to="properties.unit",
                        verbose_name="Юнит",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рекомендация цены",
                "verbose_name_plural": "Рекомендации цен",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
