# Generated by Django 5.2.8 on 2025-11-24 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("owners", "0001_initial"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckinTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("cleaning", "Уборка"),
                            ("maintenance", "Эксплуатация"),
                            ("checkin", "Заселение"),
                            ("checkout", "Выселение"),
                            ("quality_inspection", "Контроль качества"),
                            ("owner_request", "Запрос собственника"),
                        ],
                        max_length=32,
                        verbose_name="Тип задачи",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В работе"),
                            ("done", "Выполнена"),
                            ("canceled", "Отменена"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("normal", "Нормальный"),
                            ("high", "Высокий"),
                            ("critical", "Критический"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дедлайн"),
                ),
                (
                    "activity_log",
                    models.TextField(
                        blank=True,
                        help_text="Произвольный текстовый лог изменений по задаче.",
                        verbose_name="Лог действий",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "check_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время заселения"
                    ),
                ),
                (
                    "responsible_person",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Ответственный (ФИО/служба)",
                    ),
                ),
                ("checklist", models.TextField(blank=True, verbose_name="Чек-лист")),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="bookings.booking",
                        verbose_name="Бронирование",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="owners.owner",
                        verbose_name="Собственник",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="properties.property",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="properties.unit",
                        verbose_name="Юнит",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача заселения",
                "verbose_name_plural": "Задачи заселения",
            },
        ),
        migrations.CreateModel(
            name="CheckoutTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("cleaning", "Уборка"),
                            ("maintenance", "Эксплуатация"),
                            ("checkin", "Заселение"),
                            ("checkout", "Выселение"),
                            ("quality_inspection", "Контроль качества"),
                            ("owner_request", "Запрос собственника"),
                        ],
                        max_length=32,
                        verbose_name="Тип задачи",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В работе"),
                            ("done", "Выполнена"),
                            ("canceled", "Отменена"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("normal", "Нормальный"),
                            ("high", "Высокий"),
                            ("critical", "Критический"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дедлайн"),
                ),
                (
                    "activity_log",
                    models.TextField(
                        blank=True,
                        help_text="Произвольный текстовый лог изменений по задаче.",
                        verbose_name="Лог действий",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "checkout_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время выселения"
                    ),
                ),
                (
                    "responsible_person",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Ответственный (ФИО/служба)",
                    ),
                ),
                ("checklist", models.TextField(blank=True, verbose_name="Чек-лист")),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="bookings.booking",
                        verbose_name="Бронирование",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="owners.owner",
                        verbose_name="Собственник",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="properties.property",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="properties.unit",
                        verbose_name="Юнит",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача выселения",
                "verbose_name_plural": "Задачи выселения",
            },
        ),
        migrations.CreateModel(
            name="CleaningTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("cleaning", "Уборка"),
                            ("maintenance", "Эксплуатация"),
                            ("checkin", "Заселение"),
                            ("checkout", "Выселение"),
                            ("quality_inspection", "Контроль качества"),
                            ("owner_request", "Запрос собственника"),
                        ],
                        max_length=32,
                        verbose_name="Тип задачи",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В работе"),
                            ("done", "Выполнена"),
                            ("canceled", "Отменена"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("normal", "Нормальный"),
                            ("high", "Высокий"),
                            ("critical", "Критический"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дедлайн"),
                ),
                (
                    "activity_log",
                    models.TextField(
                        blank=True,
                        help_text="Произвольный текстовый лог изменений по задаче.",
                        verbose_name="Лог действий",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "is_pre_arrival",
                    models.BooleanField(
                        default=False, verbose_name="Предзаездная уборка"
                    ),
                ),
                (
                    "is_post_departure",
                    models.BooleanField(
                        default=False, verbose_name="Послезаселения уборка"
                    ),
                ),
                (
                    "is_general",
                    models.BooleanField(
                        default=False, verbose_name="Генеральная уборка"
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="bookings.booking",
                        verbose_name="Бронирование",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="owners.owner",
                        verbose_name="Собственник",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="properties.property",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="properties.unit",
                        verbose_name="Юнит",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача уборки",
                "verbose_name_plural": "Задачи уборки",
            },
        ),
        migrations.CreateModel(
            name="MaintenanceTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("cleaning", "Уборка"),
                            ("maintenance", "Эксплуатация"),
                            ("checkin", "Заселение"),
                            ("checkout", "Выселение"),
                            ("quality_inspection", "Контроль качества"),
                            ("owner_request", "Запрос собственника"),
                        ],
                        max_length=32,
                        verbose_name="Тип задачи",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В работе"),
                            ("done", "Выполнена"),
                            ("canceled", "Отменена"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("normal", "Нормальный"),
                            ("high", "Высокий"),
                            ("critical", "Критический"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дедлайн"),
                ),
                (
                    "activity_log",
                    models.TextField(
                        blank=True,
                        help_text="Произвольный текстовый лог изменений по задаче.",
                        verbose_name="Лог действий",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "issue_type",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Тип проблемы"
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Срочность"
                    ),
                ),
                (
                    "can_check_in",
                    models.BooleanField(
                        default=True, verbose_name="Можно заселять жильцов"
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="bookings.booking",
                        verbose_name="Бронирование",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="owners.owner",
                        verbose_name="Собственник",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="properties.property",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="properties.unit",
                        verbose_name="Юнит",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача по эксплуатации",
                "verbose_name_plural": "Задачи по эксплуатации",
            },
        ),
        migrations.CreateModel(
            name="OwnerRequestTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("cleaning", "Уборка"),
                            ("maintenance", "Эксплуатация"),
                            ("checkin", "Заселение"),
                            ("checkout", "Выселение"),
                            ("quality_inspection", "Контроль качества"),
                            ("owner_request", "Запрос собственника"),
                        ],
                        max_length=32,
                        verbose_name="Тип задачи",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В работе"),
                            ("done", "Выполнена"),
                            ("canceled", "Отменена"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("normal", "Нормальный"),
                            ("high", "Высокий"),
                            ("critical", "Критический"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дедлайн"),
                ),
                (
                    "activity_log",
                    models.TextField(
                        blank=True,
                        help_text="Произвольный текстовый лог изменений по задаче.",
                        verbose_name="Лог действий",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "request_details",
                    models.TextField(blank=True, verbose_name="Детали запроса"),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="bookings.booking",
                        verbose_name="Бронирование",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="owners.owner",
                        verbose_name="Собственник",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="properties.property",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="properties.unit",
                        verbose_name="Юнит",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача по запросу собственника",
                "verbose_name_plural": "Задачи по запросам собственников",
            },
        ),
        migrations.CreateModel(
            name="QualityInspectionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("cleaning", "Уборка"),
                            ("maintenance", "Эксплуатация"),
                            ("checkin", "Заселение"),
                            ("checkout", "Выселение"),
                            ("quality_inspection", "Контроль качества"),
                            ("owner_request", "Запрос собственника"),
                        ],
                        max_length=32,
                        verbose_name="Тип задачи",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В работе"),
                            ("done", "Выполнена"),
                            ("canceled", "Отменена"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("normal", "Нормальный"),
                            ("high", "Высокий"),
                            ("critical", "Критический"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дедлайн"),
                ),
                (
                    "activity_log",
                    models.TextField(
                        blank=True,
                        help_text="Произвольный текстовый лог изменений по задаче.",
                        verbose_name="Лог действий",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "scores",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Структура чек-листа и оценок (JSON).",
                        verbose_name="Оценки по чек-листу",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="bookings.booking",
                        verbose_name="Бронирование",
                    ),
                ),
                (
                    "cleaning_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_inspections",
                        to="operations.cleaningtask",
                        verbose_name="Связанная задача уборки",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="owners.owner",
                        verbose_name="Собственник",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="properties.property",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_tasks",
                        to="properties.unit",
                        verbose_name="Юнит",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача контроля качества",
                "verbose_name_plural": "Задачи контроля качества",
            },
        ),
        migrations.CreateModel(
            name="TaskPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "image",
                    models.FileField(upload_to="task_photos/", verbose_name="Фото"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружено"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото задачи",
                "verbose_name_plural": "Фото задач",
            },
        ),
    ]
