# Generated by Django 5.2.8 on 2025-11-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cleaningtask",
            name="requires_quality_inspection",
            field=models.BooleanField(
                default=False, verbose_name="Требует инспекции качества"
            ),
        ),
        migrations.AlterField(
            model_name="checkintask",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Запланирована"),
                    ("in_progress", "В работе"),
                    ("under_review", "На проверке"),
                    ("done", "Выполнена"),
                    ("canceled", "Отменена"),
                ],
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="checkouttask",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Запланирована"),
                    ("in_progress", "В работе"),
                    ("under_review", "На проверке"),
                    ("done", "Выполнена"),
                    ("canceled", "Отменена"),
                ],
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="cleaningtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Запланирована"),
                    ("in_progress", "В работе"),
                    ("under_review", "На проверке"),
                    ("done", "Выполнена"),
                    ("canceled", "Отменена"),
                ],
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancetask",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Запланирована"),
                    ("in_progress", "В работе"),
                    ("under_review", "На проверке"),
                    ("done", "Выполнена"),
                    ("canceled", "Отменена"),
                ],
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="ownerrequesttask",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Запланирована"),
                    ("in_progress", "В работе"),
                    ("under_review", "На проверке"),
                    ("done", "Выполнена"),
                    ("canceled", "Отменена"),
                ],
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="qualityinspectiontask",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Запланирована"),
                    ("in_progress", "В работе"),
                    ("under_review", "На проверке"),
                    ("done", "Выполнена"),
                    ("canceled", "Отменена"),
                ],
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
