# Generated by Django 5.2.8 on 2025-11-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_cleaningtask_requires_quality_inspection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkintask",
            name="closed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Время перевода задачи в статус 'Выполнена'. Используется для SLA.",
                null=True,
                verbose_name="Закрыта",
            ),
        ),
        migrations.AddField(
            model_name="checkouttask",
            name="closed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Время перевода задачи в статус 'Выполнена'. Используется для SLA.",
                null=True,
                verbose_name="Закрыта",
            ),
        ),
        migrations.AddField(
            model_name="cleaningtask",
            name="closed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Время перевода задачи в статус 'Выполнена'. Используется для SLA.",
                null=True,
                verbose_name="Закрыта",
            ),
        ),
        migrations.AddField(
            model_name="maintenancetask",
            name="closed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Время перевода задачи в статус 'Выполнена'. Используется для SLA.",
                null=True,
                verbose_name="Закрыта",
            ),
        ),
        migrations.AddField(
            model_name="maintenancetask",
            name="executor_comment",
            field=models.TextField(
                blank=True,
                help_text="Обязателен при закрытии задачи.",
                verbose_name="Комментарий исполнителя",
            ),
        ),
        migrations.AddField(
            model_name="ownerrequesttask",
            name="closed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Время перевода задачи в статус 'Выполнена'. Используется для SLA.",
                null=True,
                verbose_name="Закрыта",
            ),
        ),
        migrations.AddField(
            model_name="qualityinspectiontask",
            name="closed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Время перевода задачи в статус 'Выполнена'. Используется для SLA.",
                null=True,
                verbose_name="Закрыта",
            ),
        ),
        migrations.AddField(
            model_name="taskphoto",
            name="is_after",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, если фото сделано после выполнения задачи (для SLA/качества).",
                verbose_name="Фото после выполнения работ",
            ),
        ),
    ]
