# Generated by Django 5.2.8 on 2025-11-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0003_checkintask_closed_at_checkouttask_closed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancetask",
            name="ai_last_analyzed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="AI: время последнего анализа"
            ),
        ),
        migrations.AddField(
            model_name="maintenancetask",
            name="ai_problem_type",
            field=models.CharField(
                blank=True,
                help_text="Например: plumbing, electricity, appliance.",
                max_length=100,
                verbose_name="AI: тип проблемы",
            ),
        ),
        migrations.AddField(
            model_name="maintenancetask",
            name="ai_recommendation",
            field=models.TextField(
                blank=True,
                help_text="Краткое пояснение/что сделать.",
                verbose_name="AI: рекомендация",
            ),
        ),
        migrations.AddField(
            model_name="maintenancetask",
            name="ai_urgency",
            field=models.CharField(
                blank=True,
                help_text="low | medium | high | critical.",
                max_length=20,
                verbose_name="AI: срочность",
            ),
        ),
    ]
