# Generated by Django 5.2.8 on 2025-11-24 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Старый статус"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(max_length=20, verbose_name="Новый статус"),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Изменено"),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="bookings.booking",
                        verbose_name="Бронирование",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Изменил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изменение статуса брони",
                "verbose_name_plural": "Изменения статусов броней",
                "ordering": ["-changed_at"],
            },
        ),
    ]
