# Generated by Django 5.2.8 on 2025-11-25 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0002_bookingstatuslog"),
        ("properties", "0003_property_brand_name_property_checkin_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="manual, ota, telegram и т.п.",
                        max_length=50,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(verbose_name="Исходный текст отзыва/жалобы"),
                ),
                (
                    "sentiment",
                    models.CharField(
                        help_text="positive, neutral, negative",
                        max_length=20,
                        verbose_name="Тональность",
                    ),
                ),
                (
                    "categories",
                    models.JSONField(
                        default=list,
                        help_text='Например: ["cleaning", "staff", "noise"].',
                        verbose_name="Категории",
                    ),
                ),
                ("summary", models.TextField(verbose_name="Краткое резюме")),
                (
                    "suggestions",
                    models.TextField(blank=True, verbose_name="Рекомендации"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Проанализировано"
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_analyses",
                        to="bookings.booking",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_analyses",
                        to="properties.property",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_analyses",
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI-анализ отзыва",
                "verbose_name_plural": "AI-анализы отзывов",
                "ordering": ["-created_at"],
            },
        ),
    ]
