# Generated by Django 5.2.8 on 2025-11-24 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Пользователь, под которым собственник заходит в кабинет.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
